apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-rest-recreate
  labels:
    app: spring-petclinic-rest
spec:
  replicas: 4
  strategy:
    type: Recreate    #
  selector:
    matchLabels:
      app: spring-petclinic-rest
  template:
    metadata:
      labels:
        app: spring-petclinic-rest
    spec:
      containers:
      - name: spring-petclinic-rest
        image: docker.io/springcommunity/spring-petclinic-rest:3.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9966
          name: http
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi" 